apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: backend
spec:
  ports:
    - port: 3306
      targetPort: database-port
  selector:
    app: mariadb
    tier: backend
  type: ClusterIP
  
