apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise1
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress:5.3.1
          ports:
            - name: http-server
              containerPort: 80
          envFrom:
            - configMapRef:
                name: wp-config
          env:
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: WORDPRESS_DATABASE_PASSWORD
                  name: wp-secrets
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60 # Just for preventing rebooting the container too soon!
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20
 
