apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-slave
  namespace: exercise2
  labels:
    app: mariadb
    tier: backend
    role: slave
spec:
  selector:
    matchLabels:
      app: mariadb
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: mariadb
        role: slave
        tier: backend
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:10.3
          ports:
            - name: database-port
              containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_ROOT_PASSWORD
                  name: mdb-secrets
            - name: MARIADB_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_MASTER_ROOT_PASSWORD
                  name: mdb-secrets
          envFrom:
            - configMapRef:
                name: mdb-slave-config
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60 # Just for preventing rebooting the container too soon!
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            limits:
              cpu: 0.3
            requests:
              cpu: 0.1
