apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise1
spec:
  selector:
    matchLabels:
      app: wordpress
      track: stable
  template:
    metadata:
      labels:
        app: wordpress
        track: stable
    spec:
      containers:
        - image: bitnami/wordpress:5.3.1
          name: wordpress
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
          ports:
            - name: http-server
              containerPort: 80
          envFrom:
            - configMapRef:
                name: wp-maria-config
            - secretRef:
                name: wp-mariadb-secretdata
