apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      track: stable
  template:
    metadata:
      labels:
        app: wordpress
        track: stable
    spec:
      containers:
        - image: bitnami/wordpress:5.3.1
          name: wordpress
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
          ports:
            - name: http-server
              containerPort: 80
          resources:
            limits:
              memory: "2048Mi"
          # command: ["/bin/bash"]
          # args: ["-c", "'mkdir /download && cd /download && curl https://downloads.wordpress.org/plugin/hyperdb.1.6.zip && unzip hyperdb.1.6.zip && cd hyperdb && mv *.php /opt/bitnami/wordpress/wp-content/plugins && rm -rf /download'"]
          env:
            - name: MARIADB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: wp-mariadb-secretdata
                  key: db_user
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mariadb-secretdata
                  key: db_password
            - name: WORDPRESS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: wp-mariadb-secretdata
                  key: db_user
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mariadb-secretdata
                  key: db_password
            - name: MARIADB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wp-maria-config
                  key: db.host
            - name: WORDPRESS_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: wp-maria-config
                  key: db.name
            - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: wp-maria-config
                  key: db.name
            - name: BITNAMI_DEBUG
              value: 'true'