apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: exercise2
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - name: http
      port: 90
      targetPort: http-server
  selector:
    app: wordpress
