apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferferga-ckan.fullname" . }}
  labels:
    {{- include "ferferga-ckan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if and .Values.service.nodePort (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ferferga-ckan.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
