apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferferga-ckan.fullname" . }}-redis
  labels:
    app: {{ include "ferferga-ckan.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ferferga-ckan.fullname" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ferferga-ckan.fullname" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: 'bitnami/redis'
          env:          
            {{- range .Values.redisenv }}
            - name: {{ .name }}
              value: {{ .value | quote}}
          {{- end }}
          ports:
            - name: redis-port
              containerPort: 6379