apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferferga-ckan.fullname" . }}-solr
  labels:
    app: {{ include "ferferga-ckan.fullname" . }}-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ferferga-ckan.fullname" . }}-solr
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ferferga-ckan.fullname" . }}-solr
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: solr
          image: miguelaeh/solr:latest
          command:
            - 'bash'
            - '-c'
            - |
              . /opt/bitnami/base/functions
              . /opt/bitnami/base/helpers
              nami_initialize solr
              curl>'/tmp/ckan-core.tar.gz' 'http://apps-tests-artifacts.s3.amazonaws.com/ckan-core.tar.gz'
              tar xzf /tmp/ckan-core.tar.gz -C /opt/bitnami/solr/server/solr
              /opt/bitnami/solr/bin/solr -p 8983 -d /opt/bitnami/solr/server -f -force
          ports:
            - name: solr-port
              containerPort: 8983