apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-db
  namespace: exercise2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp-db
      track: stable
  template:
    metadata:
      labels:
        app: wp-db
        track: stable
    spec:
      containers:
        - image: bitnami/mariadb
          name: wp-db
          envFrom:
            - configMapRef:
                name: wp-maria-config
            - secretRef:
                name: wp-mariadb-secretdata
          ports:
            - name: database-conn
              containerPort: 3306
          resources:
            limits:
              memory: "2048Mi"
