apiVersion: v1
kind: Service
metadata:
  name: wp-db
  namespace: exercise1
  labels:
    app: wp-db
spec:
  type: ClusterIP
  ports:
    - name: database-conn
      port: 3306
      targetPort: 3306
  selector:
    app: wp-db
